server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test/**
        - id: quest-service
          uri: lb://test-service
          predicates:
            - Path=/quest/**
        - id: difficulty-service
          uri: lb://test-service
          predicates:
            - Path=/difficulty/**
        - id: testquest-service
          uri: lb://test-service
          predicates:
            - Path=/test_quest/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**